version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Check environment
          command: |
            python --version
            pip --version
            ls -la

      - run:
          name: Build and test
          command: |
            pip install poetry
            poetry install -v
            poetry run pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
